let dados = [
    //layout dos dados
    /*{
        imagem: `imagens/`,
        titulo: ``,
        ingredientes: ``,
        tempo: ``,
        porcao: ``,
        link: ``,
        tags: `tudo `,
    },*/
    {
        imagem: `imagens/hamburguerCaseiro.jpg`,
        titulo: `Hamburguer caseiro`,
        ingredientes: `1 kg de carne moída (de sua preferência),
        1 pacote de creme de cebola (daqueles instantâneos),
        1 ovo inteiro`,
        porcao: `1 porção`,
        tempo: `5min`,
        link: `https://www.tudogostoso.com.br/receita/2009-hamburguer-caseiro.html`,
        tags: `tudo Bovina Estrogonofe Parmegiana Picanha Almôndega Filé mignon Tender Filé Panela de pressão boi`,
    },
    {
        imagem: `imagens/picanha.jpg`,
        titulo: `Picanha ao Forno com Sal Grosso`,
        ingredientes: `1 peça de Picanha com aproximadamente 1 Kg,
        3 kg de sal grosso,
        4 colheres de sopa de manteiga,
        4 colheres de sopa de azeite,
        1 cebola (picada)`,
        porcao: `5 porções`,
        tempo: `2h 30min`,
        link: `https://www.tudogostoso.com.br/receita/249-picanha-ao-forno-com-sal-grosso.html`,
        tags: `tudo Bovina Estrogonofe Parmegiana Picanha Almôndega Filé mignon Tender Filé Panela de pressão boi`,
    },
    {
        imagem: `imagens/costelinha.jpg`,
        titulo: `Costelinha com molho barbecue (outback)`,
        ingredientes: `2 kg costelinhas de porco aferventadas em água quentel,
        1 colher (sopa) óleo,
        1/2 xícara (chá) açúcar mascavo,
        2 colheres (sopa) molho inglês,
        1 folha de louro,
        1/2 xícara (chá) água,
        Pimenta do reino a gosto,
        2 colheres (sopa) cebola picada,
        1/2 xícara (chá) vinagre branco,
        2 xícaras (chá) ketchup,
        1 colher (sopa) chilli em pó`,
        porcao: `5 porções`,
        tempo: `1h 10min`,
        link: `https://www.tudogostoso.com.br/receita/16251-costelinha-com-molho-barbecue-outback.html`,
        tags: `tudo Porco Estrogonofe Parmegiana Picanha Almôndega Filé mignon Tender Filé Panela de pressão`,
    },
    {
        imagem: `imagens/strogonoffFrango.jpg`,
        titulo: `Strogonoff de frango`,
        ingredientes: `3 peitos de frango cortados em cubos,
        1 cebola picada,
        1 colher de manteiga,
        1/3 copo de mostarda,
        1 copo de creme de leite,
        1 dente de alho picado,
        pimenta-do-reino a gosto,
        2 colheres (sopa) de maionese,
        1/2 copo de ketchup,
        1 copo de cogumelos,
        batata palha a gosto`,
        porcao: `10 porções`,
        tempo: `1h`,
        link: `https://www.tudogostoso.com.br/receita/2462-strogonoff-de-frango.html`,
        tags: `tudo Aves Peru Chester Fricassê Frango à milanesa Frango assado Filé de frango`,
    },
    {
        imagem: `imagens/fricasse.jpg`,
        titulo: `Fricassê de frango`,
        ingredientes: `•1 lata de creme de leite,
        1 copo de requeijão cremoso,
        2 peitos de frango desfiados,
        100 g de batata palha,
        1 pitada de sal,
        1 lata de milho verde,
        100 g de azeitona sem caroço,
        200 g de mussarela fatiada,
        1 xícara de água`,
        porcao: `5 porções`,
        tempo: `30min`,
        link: `https://www.tudogostoso.com.br/receita/10254-fricasse-de-frango.html`,
        tags: `tudo Aves Peru Chester Fricassê Frango à milanesa Frango assado Filé de frango`,
    },
    {
        imagem: `imagens/filePeixe.jpg`,
        titulo: `Filé de peixe assado`,
        ingredientes: `500 g de filé de peixe (tilápia, saint peter ou outro),
        2 tomates picadinhos,
        1 cebola média picada em cubos,
        cheiro-verde a gosto,
        1/2 colher (sopa) de sal,
        azeite a gosto,
        4 batatas grande descascada em rodelas de 0,5 centímetro de espessura,
        1/2 pimentão(se ele for grande),
        1 colher (sopa) cheia de alcaparras,
        coentro a gosto (opcional),
        1 dente de alho (pequeno) bem espremido`,
        porcao: `4 porções`,
        tempo: `40min`,
        link: `https://www.tudogostoso.com.br/receita/109052-file-de-peixe-assado.html`,
        tags: `tudo Peixes e frutos do mar Camarão Peixe Bacalhau Paella Salmão Sardinha`,
    },
    {
        imagem: `imagens/salpicaoFrango.jpg`,
        titulo: `Salpicão de frango`,
        ingredientes: `1 peito de frango (grande),
        1 lata de ervilha,
        1 lata ou 1 caixa de creme de leite,
        batata palha,
        1 tablete de caldo de galinha,
        cebolinha,
        1 lata de milho,
        1 cenoura ralada,
        uva-passa a gosto,
        sal a gosto,
        salsinha,
        cebola`,
        porcao: `15 porções`,
        tempo: `40min`,
        link: `https://www.tudogostoso.com.br/receita/2097-salpicao-de-frango.html`,
        tags: `tudo Saladas, molhos e acompanhamentos Molhos Saladas Acompanhamentos Arroz Feijão Risoto Molho branco`,
    },
    {
        imagem: `imagens/lasanhaBeringela.jpg`,
        titulo: `Lasanha de berinjela`,
        ingredientes: `3 berinjelas grandes,
        1 maço de coentro cortado em pedaços pequenos,
        300 g de queijo mussarela fatiado,
        2 colheres de azeite,
        1 lata de molho de tomate,
        azeitonas sem caroço cortadas,
        300 g de presunto fatiado,
        queijo catupiry`,
        porcao: `8 porções`,
        tempo: `40min`,
        link: `https://www.tudogostoso.com.br/receita/4430-lasanha-de-berinjela.html`,
        tags: `tudo Lasanha de berinjela Risoto Panqueca Yakisoba Escondidinho Galinhada Feijoada vegetariano`,
    },
    {
        imagem: `imagens/pureBatata.jpg`,
        titulo: `Purê de batata simples e fácil`,
        ingredientes: `1 kg de batata,
        2 colheres (sopa) de margarina,
        1 dente de alho espremido,
        1/2 xícara de leite`,
        porcao: `5 porções`,
        tempo: `1h`,
        link: `https://www.tudogostoso.com.br/receita/59-pure-de-batata.html`,
        tags: `tudo Purê Molhos Saladas Acompanhamentos Arroz Feijão Risoto Molho branco vegetariano`,
    },
    {
        imagem: `imagens/caldoVerde.jpg`,
        titulo: `Caldo verde`,
        ingredientes: `4 batatas médias,
        1 colher (sopa) de óleo,
        5 xícaras (chá) de água,
        1 lingüiça calabresa defumada cortada em rodelas,
        1 tablete de caldo de galinha,
        1 colher (sopa) rasa de sal ou a gosto,
        1 xícara (chá) de couve manteiga cortada em tiras`,
        porcao: `5 porções`,
        tempo: `30min`,
        link: `https://www.tudogostoso.com.br/receita/9031-caldo-verde.html`,
        tags: `tudo Sopas Cozidos e ensopados Panela de pressão Ensopado Caldo verde porco`,
    },
    {
        imagem: `imagens/macarraoQueijo.jpg`,
        titulo: `Macarrão com requeijão`,
        ingredientes: `500 g de penne cozido al dente,
        2 dentes de alho picados,
        200 g de requeijão de sua preferência,
        300 g de presunto picado,
        Queijo parmesão ralado,
        2 colheres (sopa) de azeite,
        1 lata de molho de tomate,
        1 lata de creme de leite,
        300 g de mussarela picada`,
        porcao: `6 porções`,
        tempo: `40min`,
        link: `https://www.tudogostoso.com.br/receita/83793-macarrao-com-requeijao.html`,
        tags: `tudo Macarrão Pizzas, empanados e calzones Lasanhas, nhoques e Cia. Pães Pizza Espaguete Panqueca Macarronada Pão de queijo massa vegetariano`,
    },
    {
        imagem: `imagens/pao.jpg`,
        titulo: `Pão caseiro`,
        ingredientes: `2 e 1/2 copos de água morna,
        1 colher de sal,
        1 copo de óleo,
        50 g de fermento de padaria,
        2 colheres (sopa) de açúcar,
        1 ovo,
        1 kg de farinha de trigo`,
        porcao: `5 porções`,
        tempo: `40min`,
        link: `https://www.tudogostoso.com.br/receita/9589-pao-caseiro.html`,
        tags: `tudo Pães Pizzas, empanados e calzones Macarrão Lasanhas, nhoques e Cia. Pizza Espaguete Panqueca Macarronada Pão de queijo massa vegetariano`,
    },
    {
        imagem: `imagens/pizza.jpg`,
        titulo: `Pizza de liquidificador fácil`,
        ingredientes: `1 xícara (chá) de leite,
        1 colher (chá) de sal,
        1 colher (sopa) de margarina,
        1 colher (sobremesa) de fermento em pó,
        1 ovo,
        1 colher (chá) de açúcar,
        1 e 1/2 xícara (chá) de farinha de trigo,
        1/2 lata de molho de tomate,
        250 g de mussarela ralada grossa,
        azeitona picada,
        2 tomates fatiados,
        orégano a gosto`,
        porcao: `10 porções`,
        tempo: `30min`,
        link: `https://www.tudogostoso.com.br/receita/93498-pizza-de-liquidificador-facil.html`,
        tags: `tudo Massas Pizzas, empanados e calzones Macarrão Lasanhas, nhoques e Cia. Pães Pizza Espaguete Panqueca Macarronada Pão de queijo massa`,
    },
    {
        imagem: `imagens/pudim.jpg`,
        titulo: `Pudim de leite condensado simples`,
        ingredientes: `1 lata de leite condensado,
        4 ovos inteiros,
        1 xícara de leite de vaca,
        1 xícara (chá) de açúcar,
        1/3 de xícara (chá) de água`,
        porcao: `20 porções`,
        tempo: `40min`,
        link: `https://www.tudogostoso.com.br/receita/3687-pudim-de-leite-condensado.html`,
        tags: `tudo Doces e sobremesas Mousses Pudins, flans Docinhos e bombons Pavês Brigadeiro Torta doce Pudim de leite em pó Light doce`,
    },
    {
        imagem: `imagens/caipirinha.jpg`,
        titulo: `Caipirinha - Original`,
        ingredientes: `1 limão grande,
        gelo a gosto,
        2 colheres de açúcar,
        cachaça`,
        porcao: `1 porção`,
        tempo: `5min`,
        link: `https://www.tudogostoso.com.br/receita/128825-caipirinha-original.html`,
        tags: `tudo Bebidas Drinks e Coquetéis alcoólicos Suco Vitamina Light bebida`,
    },
    {
        imagem: `imagens/milkshake.jpg`,
        titulo: `Milk shake (ovomaltine original)`,
        ingredientes: `2 bolas grandes de sorvete de creme,
        1 copo e 1/2 de leite,
        4 colheres de calda de chocolate ou cobertura de sorvete,
        8 colheres de ovomaltine`,
        porcao: `2 porções`,
        tempo: `10min`,
        link: `https://www.tudogostoso.com.br/receita/15577-milk-shake-ovomaltine-original.html`,
        tags: `tudo Drinks e Coquetéis não alcoólicos Suco Vitamina Light bebida doce`,
    },
    {
        imagem: `imagens/brigadeiro.jpg`,
        titulo: `Brigadeiro`,
        ingredientes: `1 caixa de leite condensado,
        7 colheres (sopa) de achocolatado ou 4 colheres (sopa) de chocolate em pó,
        1 colher (sopa) de margarina sem sal,
        chocolate granulado`,
        porcao: `30 porções`,
        tempo: `25min`,
        link: `https://www.tudogostoso.com.br/receita/114-brigadeiro.html`,
        tags: `tudo Brigadeiro Mousses Pudins, flans Docinhos e bombons Pavês Torta doce Pudim de leite em pó Light doce`,
    },
    {
        imagem: `imagens/coxinha.jpg`,
        titulo: `Coxinha prática deliciosa`,
        ingredientes: `1 xícara (chá) de água,
        2 tabletes de caldo de bacon ou costela,
        1 colher (sopa) de manteiga,
        margarina para untar a forma,
        2 xícaras (chá) de leite,
        1/2 xícara (chá) de batata cozida e amassada,
        2 e 1/2 xícaras (chá) de farinha de trigo,
        farinha de rosca,
        óleo para fritar,
        1 e 1/2 kg de frango,
        2 colheres (sopa) de azeite,
        2 dentes de alho,
        2 ovos batidos,
        Recheio,
        3 colheres (sopa) de requeijão cremoso,
        1 cebola pequena,
        tempero a gosto`,
        porcao: `40 porções`,
        tempo: `1h`,
        link: `https://www.tudogostoso.com.br/receita/1363-coxinha-pratica-deliciosa.html`,
        tags: `tudo Salgadinhos Coxinha Torta salgada Empadão Torta salgada de liquidificador Bolinho de chuva frango`,
    },
    {
        imagem: `imagens/tortaFrango.jpg`,
        titulo: `Torta de frango`,
        ingredientes: `500 g de peito de frango sem pele,
        4 colheres (sopa) de óleo,
        1 cebola picada,
        1 xícara (chá) de ervilhas,
        pimenta-do-reino a gosto,
        1/2 litro de caldo de galinha,
        1 dente de alho amassado,
        3 tomates sem pele e sem sementes,
        sal a gosto,
        250 ml de leite,
        2 ovos,
        queijo ralado a gosto,
        3/4 de xícara (chá) de óleo,
        1 e 1/2 xícara (chá) de farinha de trigo,
        1 colher (sopa) de fermento em pó`,
        porcao: `15 porções`,
        tempo: `40min`,
        link: `https://www.tudogostoso.com.br/receita/1282-torta-de-frango.html`,
        tags: `tudo Lanches Salgadinhos Coxinha Torta salgada Empadão Torta salgada de liquidificador Bolinho de chuva`,
    },
];